"""
Given: A DNA string s of length at most 1000 bp.
Return: The reverse complement sc of s. (So complement it AND reverse it)
"""

seq = "AACGACCTCGGGTATGTCTGCAACCACAGAACTAGAAACACCTCCAGTCTGCCGCTCATAAGTTTGTGCCCCATCAATCATTTCGAGAACAGAAAGTTGGGTCAGACGAGATCGATTAGGCCCCTTGGAACTCGGACGCATTACGAGTCAACATTGTCGATCATGGTTTTGCAGTTTTGGGTGGGCGGGCAAAATTGACGCTATCCGCTGCGGCCGCATACGTGTAACGTCTATCGCCGGGATATTCGATGCTGTATCCCCTCCCGAACCAACTGAGACCGGCCTACGAGGGGCGCAACGGTACAAGGAAACCATAAAGTATACTTAAGTTGTCAATTTCGGGGTACCAGCACCAATTAGACTCCGGACCCTTGGACATTCACTTATGCGGTACTACTCGACCCTTTCACAGCTAAATAATCGCCCTGCTTAGCACCGACGACCTGTGCGGACACGGTAATGTGACAAGAAGAGCTAATGAATACTTTTCGATACAGAGTGATTCGTCGTTCTACAATTACATCTTCAATGAGTGGCACAGGTAGGGACTCCGATTACGGTAAAATATCCACTTACATAAGGACCGCAACCCAAGCTGCCATTAGCACCACCGACGGCTCCATCGGGGTAGGCTGCCTCCGCGTACGAAAATCATTCGCCGTACTCTCATCTAGTGGCGGACACTCGCACTTCCGTCATCACATCACCCTGTGTTAAGGCCGGCGTCCCATTGGCCCCCCGCCTACAATGCCGCCCATTGAAGCGTGGGACGTTCTCGCATGACCTTCCAGTTTTGGGCTGCGAA"

complement = seq.replace("A", "t").replace("T", "a").replace("C", "g").replace("G", "c")
complement = complement.replace("a", "A").replace("t", "T").replace("c", "C").replace("g", "G")

reverse_complement = ''.join(reversed(complement))

print(reverse_complement)
