"""
Given: A DNA string s of length at most 1000 nt.
Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.
"""

seq = "CTCACTGATGATCAATAAAACTTGGGTTATTACAAACGAACGCTAGGGCGTTTTGGCCATCGCATTTAGAAACAGGCAATTACCGCGACAGGCTCACGCCCTAGTGACAGCTTCAATTTCTTATCTTAACAGTGAAATTCGATATTGTGACCTTCGTTGTTGTTTCGACCGACGCCGATTTAACTCCCACATAATATCCACGCTGTGGGACTAGTATTGCAGCTGTTTCGTACAGCCCGTAAGTACCGTGATGACACTTTGGATCGGTATGTACACGGTAACCAACCTTGGCATGCGAAAGTCTGCGGTTTGTTCTCAGAACTGAAGACCTTTGTTTATCGACACAAAGATGCCGACAACGTGCCTGCTATCCGAAGGGCAGCTGGAACTATTTCTAGGGCGGTTCCACGGATCATGGCCCTCTTTAGCTTTCTTACGATGACCCAATGGCTAGCCCCCTCTCACAGCCATGAAGAGGTACACCCCGGGTCTGGGATATAAAGACGAGCACATAGTCGAGGGAGGCATCAGCGTTGTAAACCATGCGCTTGCAATTAAGGCTTAAACCGGATCTCCTATATGTCGCGCGTGCAGTTTCCGTGACTGGCGCGTACGCTTAGCTACACGGCATGCTGGGGAGCTGATTACGACACTGAATACCAACCTGCACTCAGATAGCGCGACATAGAGCTCCCGTGGCATTGCAGAGCTTTTGGGCGGGGCATCCGCTCCGGGCCAACCATTGAACTCTTCGGACCAAAGTATGACCGAATGGGCATTTAAACGACCACTCGGTCTGTTACAAATGCTTCAGACGTGTGTTTTTGAGAAATGTCAGGGGTGCAAGGGTCAATAGTTACGCACTTTATAGGGAGAGCCGAATCTGTAAGAGTCATTGCATCTTACCGTCATCTTTGCCTACTTGTTAGCCCGATGT"
a_count = 0
c_count = 0
g_count = 0
t_count = 0

for letter in seq:
	if (letter == "A"):
		a_count += 1
	if (letter == "C"):
		c_count += 1
	if (letter == "G"):
		g_count += 1
	if (letter == "T"):
		t_count += 1

print(str(a_count) + " " + str(c_count) + " " + str(g_count) + " " + str(t_count))
